### ISSUE TITLE
Does this framework actually support 2016 with java scripting?  It is failing for me on 2016 and lower.

### ISSUE THREAD

**Issue by phusting** [OfficeDev/Office-Addin-TaskPane-JS#114]
# Expected behavior
I'm using this framework to create an add-in for Word.  It is working great in Word 2019 and up.   But when I try and run it in Word 2016, it is failing because it looks like Word 2016 is trying to use Internet Explorer 11 as the container for the add-in.  :o)  So any scripting fails to run.

I'm using the base of this project.

##
The big issue is I'm trying to get it in the AppSource store and am being rejected because of that Office 2016 issue and am not sure of any work around.  Is anyone monitoring this and have a suggestion?

### From MSFT AppSource
Your offer does not work in Microsoft 365 version 16.0.11629 or later without Edge WebView2 (Chromium-based) installed on Windows 10. 

Issue: Getting blank page while loading the ad-in.

Repro steps:

Open word doc
Launch the add-in
Getting blank page
Noticed an issue
Please refer to the attachment for evidence.

Update the offer to be fully functional in all required environments and resubmit your offer. This failure will not stop the offer from publishing to the store. See [Browsers Used by Office Web Addins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) for details on runtime environments.

**Comment by millerds** [comment]
I'm not sure what exactly you mean by "this framework" but yes . . . office add-in's are generally supported in the IE component used in Word 2016.  In the dev tooling we provide you are able to use pre-release versions of office (you can change the "channel you are installing if you are using the subscription version of Office) and run the command "npx office-addin-dev-settings webview manifest.xml ie" to actually tell word to run using the different hosting component (IE in the case of this example).

This page gives some details of office application support: https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
