### ISSUE TITLE
webpack-cli needs to be version ^3.3.5

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/Office-Addin-TaskPane-JS#29]
I encountered this bug yesterday, although I cannot reliably reproduce it. https://stackoverflow.com/questions/56639025/how-to-solve-typeerror-process-getuid-is-not-a-function 

Looks like the fix is to update the package.json to use webpack-cli ^3.3.5. Can this change be made just to ensure no one accidentally runs into this bug? Thanks!

**Comment by akrantz** [comment]
We already updated dependencies in https://github.com/OfficeDev/Office-Addin-TaskPane, so that just needs to be merged in here.

**Comment by davidchesnut** [comment]
Cool, thanks!

**Comment by akrantz** [comment]
Hey @davidchesnut, just so you know, when an issue is marked as fixed in the pull request, it will be closed automatically when the pull request is merged.

**Comment by davidchesnut** [comment]
Cool, thanks!
