### ISSUE TITLE
A Couple of Questions

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/Office-Addin-TaskPane-JS#75]
1. Is there a way to address this OfficeDev group as a whole? From what I can see, it is on a repository-to-repository basis.

2. Is VSTO being deprecated? I ask because I am told by some at my job that it is. However, I've seen nothing from Microsoft stating such and, with each Office release, the object model is usually extended.

**Comment by LouMM** [comment]
Hi @elthombre, OfficeDev encapsulates many teams in the Office universe. If you want to hit a large number of Office Platform (Add-ins, Custom Functions, and other areas) you could post in officejs repro. 

VSTO is not our area of expertise.

Thanks! Let us know if you have any other questions.
