### ISSUE TITLE
The input file is not supported in development mode

### ISSUE THREAD

**Issue by ficapy** [OfficeDev/Office-Addin-TaskPane-JS#97]
# Expected behavior

The HTML that is available in ScriptLab but is not available in the development environment

# Current behavior

```html
<input type="file" />
```
No response when clicked in the development environment

## Steps to Reproduce

1. yo office
2. npm start
3. run ScriptLab again

## Context

* Operating System: win 10
* Node version:  v16.13.0
* Office version:  office 365, editon 2202 Build 16.0.14931.20128
* Tool version: yo office

video below
https://www.loom.com/share/044c488ec27d4eaeb36c835b2f8f32dd

**Comment by millerds** [comment]
There is no connection between script lab and a project produced by running 'yo office' . . . they are independent add-ins.  I'm able to insert the same input tag in a project produced by running 'yo office' (assuming I was using the appropriate templated) and it works for me.  The fact that you are seeing it in both add-ins suggests there is some other underlying cause of the bahavior.
